services:
  - type: cron
    name: facebook-event-scraper
    schedule: "0 13 * * *" # Every day at 6am PST / 9am EST
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

