services:
  - type: cron
    name: facebook-events-daily
    runtime: python
    schedule: "0 10 * * *"  # runs daily at 10 AM UTC
    buildCommand: ""
    startCommand: |
      playwright install
      python main.py
